### PR TITLE
Dockerfilesk

### PR DESCRIPTION
**Pull request by scientes**
lets look if the third attempt works^

### CODE REVIEW

**Comment by lucasace** [comment]
was #56 
Sorry, that was my bad

**Comment by scientes** [comment]
ok git you just achieved to confuse me

**Comment by scientes** [comment]
why is the dockerfile itself not in the changes

**Comment by lucasace** [comment]
SHouldnt the dockerfiles have come too?

**Comment by scientes** [comment]
jup

**Comment by scientes** [comment]
ill fix it one mom

**Comment by lucasace** [comment]
Its probably because git thinks the commit is already merged , cause the two commits before revert docker file reference the inistal commits in #56

**Comment by scientes** [comment]
jup ill merge the feature final branch into this one and make the commits again

**Comment by scientes** [comment]
still need to test if it works

**Comment by lucasace** [comment]
Yeaa!!
Don't mind the white background
I removed the image directory
So that happened
Will fix it soon

**Comment by scientes** [comment]
then lets merge

**Comment by lucasace** [comment]
I need to test it though
```
docker build .
docker compose up -d
```
right?

**Comment by scientes** [comment]
> I need to test it though
> 
> ```
> docker build .
> docker compose up -d
> ```
> 
> right?

sudo docker build --pull --rm -f "DOCKERFILE" -t best11fantasycricket:latest "."
sudo docker-compose up -d

was my approach
but sudo docker build -f "DOCKERFILE" -t best11fantasycricket:latest "."
should also work

**Comment by lucasace** [comment]
You wouldnt have to use sudo if you do follow [this](https://docs.docker.com/engine/install/linux-postinstall/)
Also if you rename the files as `Dockerfile` and `Dockerfile.development` you wouldnt have to use the -f tag as well

**Comment by scientes** [comment]
> You wouldnt have to use sudo if you do follow [this](https://docs.docker.com/engine/install/linux-postinstall/)
> Also if you rename the files as `Dockerfile` and `Dockerfile.development` you wouldnt have to use the -f tag as well

yea i coudn't bother until now on my local machine

**Comment by scientes** [comment]
docker build -t best11fantasycricket:latest "."
 should work

**Comment by lucasace** [comment]
dumb question but what url do i search?
is it localhost:8000 itself?
Cuse 8000 doesnt seem to work

**Comment by scientes** [comment]
yeah beacuse localhost 80 sometimes causes hicups

**Comment by lucasace** [comment]
It works, there are still some complications with the crawler
But thats my issue , ill have to look into it

Once the frontend and this issue is resolved, we can start the hosting process
Thank you for contributing

**Pull request merged**
